matcher:
  - label: "terminal"
    criteria: "app_id"
    value: "kitty"
  - label: "browser"
    criteria: "app_id"
    value: "firefox"
  - label: "browser"
    criteria: "app_id"
    value: "Chromium"
runner:
  terminal: "new_term"
  browser: "browser"
