matcher:
  - label: "terminal"
    criteria: "app_id"
    value: "foot"
  - label: "terminal"
    criteria: "app_id"
    value: "kitty"
  - label: "browser"
    criteria: "app_id"
    value: "firefox"
  - label: "browser"
    criteria: "app_id"
    value: "chromium"
runner:
  terminal: "foot"
  browser: "browser --new-window"
