matcher:
  - label: "terminal"
    criteria: "app_id"
    value: "kitty"
  - label: "browser"
    criteria: "app_id"
    value: "firefox"
  - label: "browser"
    criteria: "app_id"
    value: "chromium"
runner:
  terminal: "kitty"
  browser: "browser"
  # browser: "firefox --new-window"
