matcher:
  - label: "editor"
    criteria: "name"
    value: "NVIM$"
  - label: "terminal"
    criteria: "app_id"
    value: "foot"
  - label: "terminal"
    criteria: "app_id"
    value: "kitty"
  - label: "terminal"
    criteria: "app_id"
    value: "tym"
  - label: "browser"
    criteria: "app_id"
    value: "firefox"
  - label: "browser"
    criteria: "app_id"
    value: "chromium"
runner:
  editor: "$TERMINAL -e sh -c .local/bin/nvim_session"
  terminal: ".local/bin/new_term"
  browser: ".local/bin/browser --new-window"
