shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "53a26e287fbbe2dcebb3aa1801546c6de32416fa"

[plugins.autopairs]
github = 'hlissner/zsh-autopair'
apply = ["defer"]
rev = "449a7c3d095bc8f3d78cf37b9549f8bb4c383f3d"

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
rev = "5eb677bb0fa9a3e60f0eff031dc13926e093df92"
