unqualified-search-registries = ["docker.io", "quay.io"]

[[registry]]
location = "us-docker.pkg.dev"
insecure = false
blocked = false

[network]
default_rootless_network_cmd = "slirp4netns"
network_cmd_options = ["enable_ipv6=false"]
