# 1. Static Configuration (The manual stuff)
music_directory    "~/Music"
playlist_directory "~/Personal/mpd"

db_file            "~/.local/state/mpd/database"
state_file         "~/.local/state/mpd/state"
sticker_file       "~/.local/state/mpd/sticker.sql"

log_file           "syslog"

pid_file           "/run/user/1000/mpd.pid" 

audio_output {
    type            "pipewire"
    name            "PipeWire Sound Server"
}
