model = "gpt-6-sol"
model_reasoning_effort = "low"
check_for_update_on_startup = false

[tui]
screen_reader_detection_done = true
show_tooltips = false

[tui.model_availability_nux]
gpt-6-astra = 4

[projects."/home/prncss/projects/nvim/main"]
trust_level = "trusted"

[projects."/home/prncss/projects/dotfiles"]
trust_level = "trusted"
