assets: Personal/zk/assets
views:
  filmsy:
    args: '--sort word-count --limit 20'
  recent:
    args: '--sort created- --limit 20'
  lucky:
    args: '--sort random --limit 20'
  orphan:
    args: '--orphan'
  kanban:
    view: board
    tags:
      - w/backlog/3
      - w/backlog/2
      - w/backlog/1
      - w/backlog/0
      - w/active
      - w/pending
      - w/follow
      - w/stable
      - w/published
      - w/completed
  focus:
    view: board
    tags:
      - w/backlog/0
      - w/active
      - w/pending
      - w/follow
