#!/bin/sh

spawn_once() {
  pgrep -f "${1}" >/dev/null || riverctl spawn "${*}"
}

UP=K
DOWN=J
LEFT=semicolon
RIGHT=L
NEXT=N
PREVIOUS=P

O_UP=I
O_DOWN=U
O_LEFT=P
O_RIGHT=O

riverctl keyboard-layout -options "caps:escape" ca

riverctl map normal Super+Control E close
riverctl map normal Super+Control Q spawn waylock
riverctl map normal Super+Control C spawn .config/river/init

riverctl map normal Super f toggle-fullscreen

riverctl map normal Super $UP focus-view next
riverctl map normal Super $DOWN focus-view previous
riverctl map normal Super $LEFT focus-view left
riverctl map normal Super $RIGHT focus-view right
riverctl map normal Super Shift $UP swap next
riverctl map normal Super Shift $DOWN swap previous
riverctl map normal Super Return zoom

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl declare-mode adjust
riverctl map normal Super r enter-mode adjust
riverctl map adjust None Escape enter-mode normal
riverctl map adjust None $LEFT send-layout-cmd rivertile "main-ratio -0.05"
riverctl map adjust None $RIGHT send-layout-cmd rivertile "main-ratio +0.05"
riverctl map adjust None $UP send-layout-cmd rivertile "main-count +1"
riverctl map adjust None $DOWN send-layout-cmd rivertile "main-count -1"
riverctl map adjust None $O_UP send-layout-cmd rivertile "main-location top"
riverctl map adjust None $O_RIGHT send-layout-cmd rivertile "main-location right"
riverctl map adjust None $O_DOWN send-layout-cmd rivertile "main-location bottom"
riverctl map adjust None $O_LEFT send-layout-cmd rivertile "main-location left"

riverctl declare-mode float
riverctl map normal Super q enter-mode float
riverctl map float None Escape enter-mode normal
# toggle
riverctl map float Super Space toggle-float
# move
riverctl map float None $LEFT move left 100
riverctl map float None $DOWN move down 100
riverctl map float None $UP move up 100
riverctl map float None $RIGHT move right 100
# resize
riverctl map float Shift $LEFT resize horizontal -100
riverctl map float Shift $DOWN resize vertical 100
riverctl map float Shift $UP resize vertical -100
riverctl map float Shift $RIGHT resize horizontal 100
# snap
riverctl map float Super+Alt+Control $O_LEFT snap left
riverctl map float Super+Alt+Control $O_DOWN snap down
riverctl map float Super+Alt+Control $O_UP snap up
riverctl map float Super+Alt+Control $O_RIGHT snap right

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
riverctl map normal Super F10 enter-mode passthrough
riverctl map passthrough Super F10 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ +4%'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ -4%'
  riverctl map $mode None XF86AudioMute spawn 'pactl set-sink-mute \@DEFAULT_SINK@ toggle'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set 2%+'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 2%-'

  riverctl map $mode Super+Control R spawn 'sudo /usr/sbin/reboot'
  riverctl map $mode Super+Control P spawn 'sudo /usr/sbin/poweroff'
  riverctl map $mode Super+Control E exit
done

riverctl declare-mode audio
riverctl map normal Super O enter-mode audio
riverctl map audio None Escape enter-mode normal
riverctl map audio None $UP spawn 'pactl set-sink-volume @DEFAULT_SINK@ +4%'
riverctl map audio None $DOWN spawn 'pactl set-sink-volume @DEFAULT_SINK@ -4%'
riverctl map audio Shift $UP spawn 'pactl set-sink-volume @DEFAULT_SINK@ +12%'
riverctl map audio Shift $DOWN spawn 'pactl set-sink-volume @DEFAULT_SINK@ -12%'
riverctl map audio None M spawn 'pactl set-sink-mute \@DEFAULT_SINK@ toggle'
riverctl map audio None space spawn 'playerctl play-pause'
riverctl map audio None $LEFT spawn 'playerctl previous'
riverctl map audio None $RIGHT spawn 'playerctl next'
riverctl map audio None X spawn 'playerctl stop'

riverctl declare-mode lumino
riverctl map normal Super I enter-mode lumino
riverctl map lumino None Escape enter-mode normal
riverctl map lumino None $UP spawn 'brightnessctl set 2%+'
riverctl map lumino None $DOWN spawn 'brightnessctl set 2%-'
riverctl map lumino Shift $UP spawn 'brightnessctl set 100%'
riverctl map lumino Shift $DOWN spawn 'brightnessctl set 0%'

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl hide-cursor timeout 1000
riverctl hide-cursor when-typing enabled

riverctl set-repeat 50 300

riverctl map normal Super+Shift D spawn 'sh -c "darkman toggle"'
riverctl map normal Super N set-focused-tags 1
riverctl map normal Super M set-focused-tags 2
riverctl map normal Super comma set-focused-tags 4
riverctl map normal Super period set-focused-tags 8
riverctl map normal Super eacute set-focused-tags 16

riverctl map normal Super+Shift N set-view-tags 1
riverctl map normal Super+Shift M set-view-tags 2
riverctl map normal Super+Shift comma set-view-tags 4
riverctl map normal Super+Shift period set-view-tags 8
riverctl map normal Super+Shift eacute set-view-tags 16

riverctl map normal Super A focus-previous-tags
riverctl map normal Super Shift A send-to-previous-tags
all_tags=$(((1 << 32) - 1))
# focus all tags
riverctl map normal Super 0 set-focused-tags $all_tags
# to tag focused view with all tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl rule-add -app-id popup float
riverctl rule-add -app-id imv ssd
riverctl rule-add -app-id firefox ssd
riverctl rule-add -title Picture-in-Picture float
riverctl rule-add -title term-prompt float
riverctl rule-add -app-id pavucontrol float
riverctl rule-add -app-id wlroot ssd
riverctl rule-add -app-id org.freedesktop.Xwayland float
riverctl rule-add -app-id org.freedesktop.Xwayland ssd

riverctl default-layout rivertile

riverctl map normal Print spawn grim
riverctl map normal Super S spawn grim
riverctl map normal Super space spawn fuzzel
riverctl map normal Super E spawn 'sh -c "neovide"' # we need this to have paths properly setup
riverctl map normal Super T spawn footclient
riverctl map normal Super+Shift T spawn "footclient -e bash"
riverctl map normal Super Y spawn .local/bin/browser
riverctl map normal Super P spawn 'sh -c "STORE_DIR=$HOME/Personal/pass/ tessen"'
riverctl map normal Super G spawn "swaync"
riverctl map normal Super+Shift G spawn "swaync-client -t"

dbus-update-activation-environment XDG_CURRENT_DESKTOP=sway WAYLAND_DISPLAY --systemd --all
turnstile-update-runit-env XDG_CURRENT_DESKTOP=sway WAYLAND_DISPLAY DISPLAY SWAYSOCK PATH
spawn_once way-displays

spawn_once rivertile -view-padding 4 -outer-padding 0
# spawn_once river-tag-overlay
spawn_once foot --server
swayidle -w \
  timeout 300 'waylock -fork-on-lock' \
  timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
  before-sleep 'waylock -fork-on-lock' &
spawn_once /usr/libexec/polkit-gnome-authentication-agent-1
sv restart polkit-gnome
spawn_once kdeconnectd
spawn_once swaync
spawn_once wlsunset -S 07:00 -s 16:00
spawn_once udiskie

$HOME/.local/bin/random-wallpaper &
spawn_once waybar
spawn_once firefox
