worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[commit.generation]
command = "p --no-tools --no-extensions --no-skills --no-context-files --model opencode-go/deepseek-v4-flash:off -p \"\""

[commit]
stage = "all"

[hooks]
post-create = ".git/hooks/post-checkout 0000000000000000000000000000000000000000 1111111111111111111111111111111111111111 1"
