[Editor]
FontFamily = 'Victor Mono'
FontSize = 8
ExtCmdline   = false
ExtPopupmenu = true
ExtTabline   = false
DesktopNotifications = true
DrawWindowSeparator = false
WindowSeparatorTheme = "dark"
WindowSeparatorColor = "#2222ff"
WindowSeparatorGradient = true
DrawBorderForFloatWindow = false
DrawShadowForFloatWindow = true

[MiniMap]
Visible = true

[Statusline]
visible = false

[Tabline]
Visible = false
