tags: [w/backlog]
noteDir: sources
removeTitle:
  words:
    - the
    - a
    - le
    - la
    - les
    - de
    - du
  prefixes:
    - d'
    - l'
  characters: '"*/:<>?\\|'
  accents: false
export:
  w/backlog/0: epubs/backlog 0
toHTML:
  name: zk-web
  args:
    - html
