tags: [w/backlog/0]
noteDir: sources
exportDir: Books
exportRm: false
removeTitle:
  words:
    - the
    - a
    - le
    - la
    - les
    - de
    - du
  prefixes:
    - d'
    - l'
  characters: '"*/:<>?\|@'
  accents: false
export:
  w/backlog/0: .
importTags:
  completed: [w/completed, review]
  stable: [w/stable]
  broken: [w/broken]
  backlog1: [w/backlog/1]
  pending: [w/pending]
  halted: [w/halted]
rmTags:
  - w
toHTML:
  name: zk-web
  args:
    - html
